<?php
/**
 * Zikula Application Framework
 *
 * @copyright (c) 2002, Zikula Development Team
 * @link http://www.zikula.org
 * @version $Id: banners.php 9 2008-11-05 21:42:16Z Guite $
 * @license GNU/GPL - http://www.gnu.org/copyleft/gpl.html
 * @package Zikula_Value_Addons
 * @subpackage Banners
 */

/**
 * initialise block
 * 
 * @author       The Zikula Development Team
 */
function Banners_bannersblock_init()
{
    // Security
    pnSecAddSchema('Bannersblock::', 'Block title::');
}

/**
 * get information on block
 * 
 * @author       The Zikula Development Team
 * @return       array       The block information
 */
function Banners_bannersblock_info()
{
    return array('text_type'       => 'banners',
                 'module'          => 'Banners',
                 'text_type_long'  => 'Custom Banner Display',
                 'allow_multiple'  => true,
                 'form_content'    => false,
                 'form_refresh'    => false,
                 'show_preview'    => true,
                 'admin_tableless' => true);
}

/**
 * display block
 * 
 * @author       The Zikula Development Team
 * @param        array       $blockinfo     a blockinfo structure
 * @return       output      the rendered bock
 */
function Banners_bannersblock_display($blockinfo)
{
    if (!SecurityUtil::checkPermission('Bannersblock::', "$blockinfo[title]::", ACCESS_READ)) {
        return;
    }

    // Get variables from content block
    $vars = pnBlockVarsFromContent($blockinfo['content']);

    // Defaults
    if (!isset($vars['btype'])) {
        $vars['btype'] = 3;
    }

    // Check if the Banners module is available. 
    if (!pnModAvailable('Banners')) {
        return false;
    }

    // Create output object
    $pnRender = pnRender::getInstance('Banners');

    // assign the banner
    $pnRender->assign('banner', pnModFunc('Banners', 'user', 'display', array('type' => $vars['btype'])));

    // Populate block info and pass to theme
    $blockinfo['content'] = $pnRender->fetch('banners_block_banners.htm');

    return pnBlockThemeBlock($blockinfo);
}

/**
 * modify block settings
 * 
 * @author       The Zikula Development Team
 * @param        array       $blockinfo     a blockinfo structure
 * @return       output      the block form
 */
function Banners_bannersblock_modify($blockinfo)
{
    // Get current content
    $vars = pnBlockVarsFromContent($blockinfo['content']);

    // Defaults
    if (!isset($vars['btype'])) {
        $vars['btype'] = 3;
    }

    // Create output object
    $pnRender = pnRender::getInstance('Banners', false);

    // assign the approriate values
    $pnRender->assign($vars);

    // Return the output that has been generated by this function
    return $pnRender->fetch('banners_block_banners_modify.htm');
}

/**
 * update block settings
 * 
 * @author       The Zikula Development Team
 * @param        array       $blockinfo     a blockinfo structure
 * @return       $blockinfo  the modified blockinfo structure
 */
function Banners_bannersblock_update($blockinfo)
{
    // Get current content
    $vars = pnBlockVarsFromContent($blockinfo['content']);

    // alter the corresponding variable
    $vars['btype'] = FormUtil::getPassedValue('btype', null, 'POST');

    // write back the new contents
    $blockinfo['content'] = pnBlockVarsToContent($vars);

    // clear the block cache
    $pnRender = pnRender::getInstance('Banners');
    $pnRender->clear_cache('banners_block_banners.htm');

    return $blockinfo;
}
